# Generated by Django 2.1.5 on 2019-01-05 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('phone_no', models.IntegerField(max_length=20)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('phone_no', models.IntegerField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('pic_location', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('phone_no', models.IntegerField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('pic_location', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.Student'),
        ),
        migrations.AddField(
            model_name='class',
            name='t_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.Teacher'),
        ),
    ]
