# Generated by Django 2.1.5 on 2019-01-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_class_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='s_id',
            new_name='s',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='t_id',
            new_name='t',
        ),
    ]
