# Generated by Django 2.1.5 on 2019-06-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20190112_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.Course')),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.Department')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.Teacher')),
            ],
        ),
        migrations.RemoveField(
            model_name='class',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='class',
            name='dep_id',
        ),
        migrations.RemoveField(
            model_name='class',
            name='t_id',
        ),
    ]
