# Generated by Django 2.1.5 on 2019-01-05 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20190105_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.Course')),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.Course')),
                ('d', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.Course')),
                ('t', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.Teacher')),
            ],
        ),
    ]
