# Generated by Django 2.1.5 on 2019-01-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_enroll_offers_teaches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='phone_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
