# Generated by Django 2.1.5 on 2019-01-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20190105_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_no',
            field=models.IntegerField(max_length=20),
        ),
    ]
