# Generated by Django 2.1.5 on 2019-01-06 12:28

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20190106_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True),
        ),
    ]
