# Generated by Django 2.1.5 on 2019-01-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20190106_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='class',
            name='date',
        ),
        migrations.AddField(
            model_name='attends',
            name='cl_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Class'),
        ),
    ]
