# Generated by Django 2.1.5 on 2019-01-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_auto_20190106_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='attends',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
